---
- hosts: all
  become: yes
  tasks:
  - name: Update the package twingate
    package:
      name: twingate
      state: latest
  - name: Restart the twingate service
    service:
      name: twingate
      state: restarted
