---
- hosts: all
  become: yes
  tasks:
  - name: Update the package nginx
    package:
      name: twingate
      state: latest
  - name: Restart the nginx service
    service:
      name: twingate
      state: restarted
