---
- hosts: all
  become: yes
  tasks:

  - name: Update Package Cache (apt/Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Update Package Cache (dnf/CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Update Package Cache (yum/Amazon)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Amazon"

  - name: Update Package Cache (yum/RedHat)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"



  - name: Update the package twingate connector
    package:
      name: twingate-connector
      state: latest
    register: updated

  - name: Restart the twingate service connector
    service:
      name: twingate-connector
      state: restarted
    when: updated.changed
